image: samueldebruyn/debian-git

pipelines:
  branches:
    gh-pages:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/$PATH_TO_WEBSITE/